### ISSUE TITLE
Not working when using typeorm 0.3.6

### ISSUE THREAD

**Issue by itsrafsanjani** [join-com/class-validators#69]
I guess this package was not updated for typeorm v3. Can you update this package please or give me any suggestion to make it work?

Error log:

```
(node:11020) UnhandledPromiseRejectionWarning: ConnectionNotFoundError: Connection "default" was not found.
    at ConnectionManager.get (C:\Users\User\Desktop\blog-nodejs\src\connection\ConnectionManager.ts:43:32)
    at Object.getRepository (C:\Users\User\Desktop\blog-nodejs\src\globals.ts:182:10)
    at IsUniqConstraint.validate (C:\Users\User\Desktop\blog-nodejs\node_modules\@join-com\typeorm-class-validator-is-uniq\src\index.ts:24:24)
    at C:\Users\User\Desktop\blog-nodejs\node_modules\src\validation\ValidationExecutor.ts:266:68
    at Array.forEach (<anonymous>)
    at C:\Users\User\Desktop\blog-nodejs\node_modules\src\validation\ValidationExecutor.ts:248:82
    at Array.forEach (<anonymous>)
    at ValidationExecutor.customValidations (C:\Users\User\Desktop\blog-nodejs\node_modules\src\validation\ValidationExecutor.ts:247:15)
    at ValidationExecutor.performValidations (C:\Users\User\Desktop\blog-nodejs\node_modules\src\validation\ValidationExecutor.ts:207:10)
    at C:\Users\User\Desktop\blog-nodejs\node_modules\src\validation\ValidationExecutor.ts:109:14
(Use `node --trace-warnings ...` to show where the warning was created)
(node:11020) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:11020) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:11020) UnhandledPromiseRejectionWarning: ConnectionNotFoundError: Connection "default" was not found.
    at ConnectionManager.get (C:\Users\User\Desktop\blog-nodejs\src\connection\ConnectionManager.ts:43:32)
    at Object.getRepository (C:\Users\User\Desktop\blog-nodejs\src\globals.ts:182:10)
    at IsUniqConstraint.validate (C:\Users\User\Desktop\blog-nodejs\node_modules\@join-com\typeorm-class-validator-is-uniq\src\index.ts:24:24)
    at C:\Users\User\Desktop\blog-nodejs\node_modules\src\validation\ValidationExecutor.ts:266:68
    at Array.forEach (<anonymous>)
    at C:\Users\User\Desktop\blog-nodejs\node_modules\src\validation\ValidationExecutor.ts:248:82
    at Array.forEach (<anonymous>)
    at ValidationExecutor.customValidations (C:\Users\User\Desktop\blog-nodejs\node_modules\src\validation\ValidationExecutor.ts:247:15)
    at ValidationExecutor.performValidations (C:\Users\User\Desktop\blog-nodejs\node_modules\src\validation\ValidationExecutor.ts:207:10)
    at C:\Users\User\Desktop\blog-nodejs\node_modules\src\validation\ValidationExecutor.ts:109:14
(node:11020) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
```

**Comment by saeidzebardast** [comment]
Same issue with typeorm 0.3.11
